### ISSUE TITLE
Build problems due to shared directory

### ISSUE THREAD

**Issue by psarahdactyl** [alecjacobson/geometry-processing-mesh-reconstruction#18]
I come across problems when I try to build the assignment. At first, it says that libigl wasn't found, so I cloned that too. But now I get the following error when running` cmake ..`

> CMake Deprecation Warning at C:/Users/sak/Documents/courses/geometry-processing/libigl/shared/cmake/CMakeLists.txt:4 (message):
>   shared/cmake/CMakeLists.txt is deprecated.  Use libigl.cmake instead.
> 
> 
> CMake Error at C:/Users/sak/Documents/courses/geometry-processing/libigl/shared/cmake/CMakeLists.txt:27 (message):
>   LIBIGL_WITH_VIEWER=ON requires LIBIGL_WITH_OPENGL_GLFW=ON and
>   LIBIGL_WITH_OPENGL=ON
> 
> 
> -- Configuring incomplete, errors occurred!

I think this particular version of the shared directory isn't the right one?

**Comment by psarahdactyl** [comment]
Yes.

**Comment by psarahdactyl** [comment]
I tried re-cloning it and now I get

> Cloning into 'C:/Users/sak/Documents/courses/geometry-processing/geometry-processing-mesh-reconstruction/shared/libigl'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:libigl/libigl.git' into submodule path 'C:/Users/sak/Documents/courses/geometry-processing/geometry-processing-mesh-reconstruction/shared/libigl' failed
> Failed to clone 'libigl'. Retry scheduled
> Cloning into 'C:/Users/sak/Documents/courses/geometry-processing/geometry-processing-mesh-reconstruction/shared/libigl'...
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:libigl/libigl.git' into submodule path 'C:/Users/sak/Documents/courses/geometry-processing/geometry-processing-mesh-reconstruction/shared/libigl' failed
> Failed to clone 'libigl' a second time, aborting
> Failed to recurse into submodule path 'shared'

**Comment by amnelles** [comment]
Not sure if an answer to this has been found but I have the same issue. I get the above error message after typing: git clone --recursive http://github.com/amnelles/geometry-processing-mesh-reconstruction.git

**Comment by MichelleArk** [comment]
Also having the same issue, using git clone --recursive

**Comment by tianhao-david-hu** [comment]
Same issue here.

**Comment by alecjacobson** [comment]
ahh, sorry everyone. 

It seems to be a permission problem that's hard for me to test (since I have permission). I just updated the repo. Could somebody try a fresh fork and  clone --recursive?

**Comment by tianhao-david-hu** [comment]
This is what I get on my terminal:
----------------------------------
Submodule 'libigl' (git@github.com:libigl/libigl.git) registered for path 'shared/libigl'
Cloning into '/Users/david/Documents/GraduateSchool/geometry-processing-mesh-reconstruction/shared/libigl'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?

**Comment by MichelleArk** [comment]
I've just created a fresh fork and tried again and also getting the exact same behaviour as above. @tianhao-david-hu, were you able to resolve the problem?

**Comment by tianhao-david-hu** [comment]
@MichelleArk Sorry, I didn't get a chance to do it. I think I'll clone the repo as the professor suggested. That can at least allow us to get started on the assignment.

**Comment by alecjacobson** [comment]
@MichelleArk Could you check what's in the `shared/.gitmodules` file, e.g., using `cat shared/.gitmodules` ?

You _should_ see:
```
[submodule "libigl"]
	path = libigl
	url = https://github.com/libigl/libigl.git
```

If the url looks different, like

```
        url = git@github.com:libigl/libigl.git
```

Then you'll need to:

1. on GitHub _delete_ your fork mesh-reconstruction,
2. re-fork mesh-reconstruction,
3. git clone --recursive http://github.com/[username]/geometry-processing-mesh-reconstruction.git

I'm not sure why this wasn't an issue last year, but I'll fix the subsequent homeworks...

**Comment by MichelleArk** [comment]
@alecjacobson I had the correct url under `shared/.gitmodules` so I don't think that's the issue for me.

It was very hacky but I just manually filled in the libigl repos that didn't make it from my `git clone --recursive` in order to get started on the assignment.

**Comment by alecjacobson** [comment]
Strange. I will keep investigating.

**Comment by GavinBarill** [comment]
Hmm I'm still having this exact same problem

**Comment by tianhao-david-hu** [comment]
I experienced some issue pushing the code after manually copying that folder, so I created a new fork and tried again. Interestingly, newly forked repo works without any interventions.

**Comment by Monica-Xiao** [comment]
hey, guys. I am a newbie for libigl, and I am trying to operate the coding of Developable surface for triangle mesh which requires the libigl package. when I use cmake to configure the cmake.list, it shows the same problem. However, I have tried to download the files of the shared file manually, but still have the problem. My computer is Win system. May I have any suggestions?  thank you

**Comment by alecjacobson** [comment]
Hi Monica,
Please post your errors on the github issue page for libigl. This page is
for a class assignment.
Alec
