### ISSUE TITLE
Ringing Artifact in my mesh

### ISSUE THREAD

**Issue by MianWei8** [alecjacobson/geometry-processing-mesh-reconstruction#21]
<img width="875" alt="screen shot 2018-01-28 at 2 43 21 pm" src="https://user-images.githubusercontent.com/23260226/35487750-1fb5b210-044d-11e8-98ac-3707e1d85d3b.png">

Am I supposed to be seeing these ringing artifacts? I ask this because in Kazhdan's paper, none of the meshes looked like they have any ringing artifacts and I can't imagine that they were using much higher resolution meshes. I could be wrong though

**Comment by tianhao-david-hu** [comment]
IMHO, I remember the professor's handout file mentions that the Kazhdan's paper uses the adaptive grid instead of a fixed grid as our simplified version does. I guess that's their secret ingredient for eliminating artifact in the shallow area of the geometry.

**Comment by dknyxh** [comment]
I'm having the same artifact. It appears that the ringing have the most impact along those axises of the constructed grid. I'm wondering if it has anything to do with the spacing of the grid at each end of those corresponding point cloud.

**Comment by alecjacobson** [comment]
Yes, these artifacts are typical for low-res grids.
