### ISSUE TITLE
Trilinear interpolation

### ISSUE THREAD

**Issue by AdamSturge** [alecjacobson/geometry-processing-mesh-reconstruction#3]
In Trilinear interpolation as it's presented in the ReadMe and the [ wiki page ](https://en.wikipedia.org/wiki/Trilinear_interpolation) it is a means to compute a scalar valued function at points laying off the latice. However in the first task it seems to me that we aren't looking to compute a scalar value but the [convex combination ](https://en.wikipedia.org/wiki/Convex_combination) of lattice points needed to produce the query points in P.  Is this correct? If it is then is it safe to say that each point in P will be expressed as a convex combination of 8 lattice points?

**Comment by patrick-boc** [comment]
What is the dimension of x? Is it (nx * ny * nz x 1) or (nx * ny * nz x 3)?

**Comment by Ming-Yeung-Alfred-Meng** [comment]
It has to be nx * ny * nz x 3 for the multiplication to make sense.
