### ISSUE TITLE
Is there any chance to get the hidden code?

### ISSUE THREAD

**Issue by FrankEscobar** [alecjacobson/geometry-processing-mesh-reconstruction#37]
As the title suggest, is there any chance to get the cpp files to check the results against https://github.com/mkazhdan/PoissonRecon ?

Thank you in advance.

**Comment by alecjacobson** [comment]
Instructors of courses can email me directly for the solution code.

I wouldn't use this assignment in production. It will be way too slow and does not consider noisy data in a principled way.
