### ISSUE TITLE
OpenGL on macOS 10.14

### ISSUE THREAD

**Issue by songfeil** [alecjacobson/geometry-processing-mesh-reconstruction#41]
Hi,

I just updated my macOS yesterday and then I found that the program just shows black screen at launch, even if I re-cloned and then didn't make changes to the code.

**Comment by pomonam** [comment]
Hello,

I have a couple of questions.
-Does it output any error? 
-Before the upgrade, was the program running?
If you think it is OpenGL issue, try "OpenGL Profiler" to debug the issue.

-Juhan

**Comment by songfeil** [comment]
Hi,

Thanks for the advice. I now find that although the program start up black screen, if I move the window a little bit from it's original place, it will render again as normal state.

Also, I think it's a very interesting problem since:
- There's no error output for the program.
- My own simplest program (which just draw a triangle) with openGL, glfw, glad also have this problem, and can also be fixed with moving the window.
- Before the upgrade the program was running fine, and the executable file generated by the previous os can work perfectly on the upgraded system. However after I upgraded the system and reload CMakeFile.txt, the problem generates.

But I'm really happy that the problem can be solved. I hear that opengl is going to be deprecated in future macOS releases and I'm not sure if this is related to that. Thanks for your help!

**Comment by alecjacobson** [comment]
Is moving the window (keeping the same size) enough? Or do you have to resize?

**Comment by songfeil** [comment]
Yes, keeping the same size is enough, didn't try to resize the window.
