### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by MichaelWes** [alecjacobson/geometry-processing-mesh-reconstruction#63]
I tried this on Windows and Mac and the latter had a more verbose error output:

mike@Michaels-MacBook-Air:~/Documents/CS/CSC419/geometry-processing-mesh-reconstruction/build$ cmake ..
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found libtool - /usr/bin/libtool
* Closing connection 1
* Closing connection 0
* Closing connection 1
* Closing connection 0
* Closing connection 1
* Closing connection 0
* Closing connection 1
* Closing connection 0
* Closing connection 1
* Closing connection 0
* Closing connection 1
* Closing connection 0
CMake Error at .cache/eigen/eigen-download-prefix/src/eigen-download-stamp/download-eigen-download.cmake:159 (message):
  Each download failed!

    error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Tue, 22 Sep 2020 03:44:07 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

    Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 443 (#1)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [227 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [100 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2895 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [148 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256

  ALPN, server accepted to use h2

  Server certificate:

   subject: businessCategory=Private Organization; jurisdictionCountryName=US; jurisdictionStateOrProvinceName=Delaware; serialNumber=3928449; C=US; ST=California; L=San Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbucket.org
   start date: Mar 27 00:00:00 2020 GMT
   expire date: May 23 12:00:00 2022 GMT
   subjectAltName: host "bitbucket.org" matched cert's "bitbucket.org"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
   SSL certificate verify ok.

  Using HTTP2, server supports multi-use

  Connection state changed (HTTP/2 confirmed)

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  Using Stream ID: 1 (easy handle 0x7fe894022800)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/2

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  Connection state changed (MAX_CONCURRENT_STREAMS == 200)!

  The requested URL returned error: 404

  stopped the pause stream!

  Connection #1 to host bitbucket.org left intact

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Tue, 22 Sep 2020 03:44:07 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

    Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 443 (#1)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [227 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [100 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2895 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [148 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256

  ALPN, server accepted to use h2

  Server certificate:

   subject: businessCategory=Private Organization; jurisdictionCountryName=US; jurisdictionStateOrProvinceName=Delaware; serialNumber=3928449; C=US; ST=California; L=San Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbucket.org
   start date: Mar 27 00:00:00 2020 GMT
   expire date: May 23 12:00:00 2022 GMT
   subjectAltName: host "bitbucket.org" matched cert's "bitbucket.org"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
   SSL certificate verify ok.

  Using HTTP2, server supports multi-use

  Connection state changed (HTTP/2 confirmed)

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  Using Stream ID: 1 (easy handle 0x7fe89500fa00)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/2

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  Connection state changed (MAX_CONCURRENT_STREAMS == 200)!

  The requested URL returned error: 404

  stopped the pause stream!

  Connection #1 to host bitbucket.org left intact

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.1...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.1) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Tue, 22 Sep 2020 03:44:13 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

    Trying 18.205.93.1...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.1) port 443 (#1)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [227 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [100 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2895 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [147 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256

  ALPN, server accepted to use h2

  Server certificate:

   subject: businessCategory=Private Organization; jurisdictionCountryName=US; jurisdictionStateOrProvinceName=Delaware; serialNumber=3928449; C=US; ST=California; L=San Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbucket.org
   start date: Mar 27 00:00:00 2020 GMT
   expire date: May 23 12:00:00 2022 GMT
   subjectAltName: host "bitbucket.org" matched cert's "bitbucket.org"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
   SSL certificate verify ok.

  Using HTTP2, server supports multi-use

  Connection state changed (HTTP/2 confirmed)

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  Using Stream ID: 1 (easy handle 0x7fe894022e00)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/2

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  Connection state changed (MAX_CONCURRENT_STREAMS == 200)!

  The requested URL returned error: 404

  stopped the pause stream!

  Connection #1 to host bitbucket.org left intact

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.0...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.0) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Tue, 22 Sep 2020 03:44:18 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

    Trying 18.205.93.0...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.0) port 443 (#1)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [227 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [100 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2895 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [148 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256

  ALPN, server accepted to use h2

  Server certificate:

   subject: businessCategory=Private Organization; jurisdictionCountryName=US; jurisdictionStateOrProvinceName=Delaware; serialNumber=3928449; C=US; ST=California; L=San Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbucket.org
   start date: Mar 27 00:00:00 2020 GMT
   expire date: May 23 12:00:00 2022 GMT
   subjectAltName: host "bitbucket.org" matched cert's "bitbucket.org"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
   SSL certificate verify ok.

  Using HTTP2, server supports multi-use

  Connection state changed (HTTP/2 confirmed)

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  Using Stream ID: 1 (easy handle 0x7fe89480ac00)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/2

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  Connection state changed (MAX_CONCURRENT_STREAMS == 200)!

  The requested URL returned error: 404

  stopped the pause stream!

  Connection #1 to host bitbucket.org left intact

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Tue, 22 Sep 2020 03:44:33 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

    Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 443 (#1)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [227 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [100 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2895 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [149 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256

  ALPN, server accepted to use h2

  Server certificate:

   subject: businessCategory=Private Organization; jurisdictionCountryName=US; jurisdictionStateOrProvinceName=Delaware; serialNumber=3928449; C=US; ST=California; L=San Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbucket.org
   start date: Mar 27 00:00:00 2020 GMT
   expire date: May 23 12:00:00 2022 GMT
   subjectAltName: host "bitbucket.org" matched cert's "bitbucket.org"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
   SSL certificate verify ok.

  Using HTTP2, server supports multi-use

  Connection state changed (HTTP/2 confirmed)

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  Using Stream ID: 1 (easy handle 0x7fe894021000)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/2

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  Connection state changed (MAX_CONCURRENT_STREAMS == 200)!

  The requested URL returned error: 404

  stopped the pause stream!

  Connection #1 to host bitbucket.org left intact

  

         --- LOG END ---
         error: downloading 'http://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 80 (#0)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/1.1

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  HTTP/1.1 301 Moved Permanently

  Content-Type: text/html

  Date: Tue, 22 Sep 2020 03:45:34 GMT

  Location: https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz

  Connection: Keep-Alive

  Content-Length: 0

  

  Connection #0 to host bitbucket.org left intact

  Issue another request to this URL:
  'https://bitbucket.org/eigen/eigen/get/3.2.10.tar.gz'

    Trying 18.205.93.2...

  TCP_NODELAY set

  Connected to bitbucket.org (18.205.93.2) port 443 (#1)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [227 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [100 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2895 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [147 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256

  ALPN, server accepted to use h2

  Server certificate:

   subject: businessCategory=Private Organization; jurisdictionCountryName=US; jurisdictionStateOrProvinceName=Delaware; serialNumber=3928449; C=US; ST=California; L=San Francisco; O=Atlassian, Inc.; OU=Bitbucket; CN=bitbucket.org
   start date: Mar 27 00:00:00 2020 GMT
   expire date: May 23 12:00:00 2022 GMT
   subjectAltName: host "bitbucket.org" matched cert's "bitbucket.org"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
   SSL certificate verify ok.

  Using HTTP2, server supports multi-use

  Connection state changed (HTTP/2 confirmed)

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  Using Stream ID: 1 (easy handle 0x7fe896009000)

  GET /eigen/eigen/get/3.2.10.tar.gz HTTP/2

  Host: bitbucket.org

  User-Agent: curl/7.64.1

  Accept: */*

  

  Connection state changed (MAX_CONCURRENT_STREAMS == 200)!

  The requested URL returned error: 404

  stopped the pause stream!

  Connection #1 to host bitbucket.org left intact

  

         --- LOG END ---
         
    

make[2]: *** [eigen-download-prefix/src/eigen-download-stamp/eigen-download-download] Error 1
make[1]: *** [CMakeFiles/eigen-download.dir/all] Error 2
make: *** [all] Error 2
CMake Error at libigl/cmake/DownloadProject.cmake:179 (message):
  Build step for eigen failed: 2
Call Stack (most recent call first):
  libigl/cmake/LibiglDownloadExternal.cmake:14 (download_project)
  libigl/cmake/LibiglDownloadExternal.cmake:52 (igl_download_project)
  libigl/cmake/libigl.cmake:101 (igl_download_eigen)
  cmake/FindLIBIGL.cmake:36 (include)
  CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/mike/Documents/CS/CSC419/geometry-processing-mesh-reconstruction/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.log](https://github.com/alecjacobson/geometry-processing-mesh-reconstruction/files/5259089/CMakeOutput.log)

**Comment by psarahdactyl** [comment]
Weird, I also get this issue
