### ISSUE TITLE
Processing README.md TeX

### ISSUE THREAD

**Issue by MichaelWes** [alecjacobson/geometry-processing-mesh-reconstruction#64]
I tried the suggestion from A1 with multimarkdown on mac OS, however most of the variables and blackboard bold end up highlighted in red and with a backslash; is that intended or just an artifact of something wrong on my end?

I also tried a marketplace extension through vscode but no luck there either.

Any help would be much appreciated!

**Comment by psarahdactyl** [comment]
I am able to see the equations after cloning the repo and opening the README.html in a browser. I've never tried the multimarkdown thing before

**Comment by MichaelWes** [comment]
Good point; I opened it in MS Edge and it renders equations nicely. Thanks
