### ISSUE TITLE
infinite space Poisson's equation

### ISSUE THREAD

**Issue by ZewenShen** [alecjacobson/geometry-processing-mesh-reconstruction#67]
As there's no boundary condition enforced in the problem, our Poisson's equation is an infinite space one? The Green's function of such a problem is known analytically, will it be equivalent to solve for the implicit function via the Green's function (computing the convolution-like integral)?

**Comment by alecjacobson** [comment]
Here's a hint: we're minimizing Dirichlet energy. Of all possible boundary conditions on the resulting Possion equation, which would induce the least Dirichlet energy?

**Comment by ZewenShen** [comment]
I guess homogenous Neumann boundary condition?
